### ISSUE TITLE
Unable to compile with SwaggerUI 3 and Angular

### ISSUE THREAD

**Issue by luca86r** [intesys/generator-jhipster-apiutils#4]
I try to install this module in a just generated JHipster project using Angular but after the installation the build process fails.

My .yo-rc.json file:
> {
  "generator-jhipster": {
    "promptValues": {
      "packageName": "it.iopenway.bff.esp",
      "nativeLanguage": "it"
    },
    "jhipsterVersion": "6.1.2",
    "applicationType": "monolith",
    "baseName": "aaa",
    "packageName": "it.iopenway.bff.esp",
    "packageFolder": "it/iopenway/bff/esp",
    "serverPort": "8080",
    "authenticationType": "jwt",
    "cacheProvider": "ehcache",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": false,
    "serviceDiscoveryType": false,
    "buildTool": "maven",
    "enableSwaggerCodegen": true,
    "jwtSecretKey": "YWRmMjZlM2M5ODYzYWFjODg4ODk0YTUwZWMwMGZiYzVhMmMyMGIxYTI2ZmQ3YmFlZWZlMDE0MjhkZjcyMzU0M2Y0ZTM2MGJiNTM4ZGQyNDU2YTdhMjQxZDRhZjc5MTRkMTFhYjdlMGJkMzMxZDdmMDZiZmNhYzEwNmNiMGVlNjA=",
    "useSass": true,
    "clientPackageManager": "npm",
    "clientFramework": "angularX",
    "clientTheme": "none",
    "clientThemeVariant": "",
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "nativeLanguage": "it",
    "languages": ["it"]
  }
}

Module installation step:
- `yo jhipster-apiutils`
- api base path: `/api`
- upgrade swagger UI to version 3: `yes`

After installing the module, this is the output of the command `./mvnw`:

> $ ./mvnw 
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< it.iopenway.bff.esp:aaa >-----------------------
[INFO] Building Aaa 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] >>> spring-boot-maven-plugin:2.1.6.RELEASE:run (default-cli) > test-compile @ aaa >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:copy-resources (default-resources) @ aaa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 16 resources
[INFO] 
[INFO] --- maven-resources-plugin:3.1.0:resources (default-resources) @ aaa ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] Copying 16 resources
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-versions) @ aaa ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M1:enforce (enforce-dependencyConvergence) @ aaa ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.8.4:prepare-agent (pre-unit-tests) @ aaa ---
[INFO] argLine set to -javaagent:/home/luca/.m2/repository/org/jacoco/org.jacoco.agent/0.8.4/org.jacoco.agent-0.8.4-runtime.jar=destfile=/tmp/aaa/target/jacoco/test.exec -Djava.security.egd=file:/dev/./urandom -Xmx256m
[INFO] 
[INFO] --- properties-maven-plugin:1.0.0:read-project-properties (default) @ aaa ---
[INFO] 
[INFO] --- openapi-generator-maven-plugin:4.0.2:generate (default) @ aaa ---
[WARNING] Output directory does not exist, or is inaccessible. No file (.openapi-generator-ignore) will be evaluated.
[INFO] OpenAPI Generator: spring (server)
[INFO] Generator 'spring' is considered stable.
[INFO] ----------------------------------
[INFO] Environment variable JAVA_POST_PROCESS_FILE not defined so the Java code may not be properly formatted. To define it, try 'export JAVA_POST_PROCESS_FILE="/usr/local/bin/clang-format -i"' (Linux/Mac)
[INFO] NOTE: To enable file post-processing, 'enablePostProcessFile' must be set to `true` (--enable-post-process-file for CLI).
[INFO] Invoker Package Name, originally not set, is now derived from api package name: it.iopenway.bff.esp.web
[INFO] writing file /tmp/aaa/target/generated-sources/openapi/src/main/java/it/iopenway/bff/esp/web/api/ApiUtil.java
[INFO] writing file /tmp/aaa/target/generated-sources/openapi/.openapi-generator-ignore
[INFO] writing file /tmp/aaa/target/generated-sources/openapi/.openapi-generator/VERSION
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.6:install-node-and-npm (install node and npm) @ aaa ---
[INFO] Node v10.16.0 is already installed.
[INFO] NPM 6.9.0 is already installed.
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.6:npm (npm install) @ aaa ---
[INFO] Running 'npm install' in /tmp/aaa
[WARNING] npm WARN @ng-bootstrap/ng-bootstrap@4.2.1 requires a peer of @angular/common@^7.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @ng-bootstrap/ng-bootstrap@4.2.1 requires a peer of @angular/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN @ng-bootstrap/ng-bootstrap@4.2.1 requires a peer of @angular/forms@^7.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN bootstrap@4.3.1 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
[WARNING] npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
[WARNING] npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
[ERROR] 
[INFO] audited 904706 packages in 6.006s
[INFO] found 2 high severity vulnerabilities
[INFO]   run `npm audit fix` to fix them, or `npm audit` for details
[INFO] 
[INFO] --- frontend-maven-plugin:1.7.6:npm (webpack build dev) @ aaa ---
[INFO] npm not inheriting proxy config from Maven
[INFO] Running 'npm run webpack:build' in /tmp/aaa
[INFO] 
[INFO] > aaa@0.0.0 webpack:build /tmp/aaa
[INFO] > npm run cleanup && npm run webpack:build:main
[INFO] 
[INFO] 
[INFO] > aaa@0.0.0 cleanup /tmp/aaa
[INFO] > rimraf target/classes/static/ target/classes/aot
[INFO] 
[INFO] 
[INFO] > aaa@0.0.0 webpack:build:main /tmp/aaa
[INFO] > npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal
[INFO] 
[INFO] 
[INFO] > aaa@0.0.0 webpack /tmp/aaa
[INFO] > node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"
[INFO] 
[INFO] Webpack: Starting ...
[INFO] Starting type checking service...
Webpack: Starting ...
[INFO] 
[INFO]    ✔ Compile modules
[INFO]    ✔ Build modules
[INFO]    ✔ Optimize modules
[INFO]    ✔ Emit files
[INFO] 
[INFO] Webpack: Finished after 7.313 seconds.
[INFO] 
[INFO]  ERROR  Failed to compile with 1 errors9:39:12 AM
[INFO] 
[INFO]  error  
[INFO] 
[INFO] 
[INFO]    594 modules
[INFO] 
[INFO] ERROR in MergeJsonWebpackPlugin: "groupBy" must be non empty object
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 2
[ERROR] npm ERR! aaa@0.0.0 webpack: `node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js "--config" "webpack/webpack.dev.js" "--env.stats=minimal"`
[ERROR] npm ERR! Exit status 2
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the aaa@0.0.0 webpack script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/luca/.npm/_logs/2019-07-26T07_39_12_101Z-debug.log
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 2
[ERROR] npm ERR! aaa@0.0.0 webpack:build:main: `npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal`
[ERROR] npm ERR! Exit status 2
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the aaa@0.0.0 webpack:build:main script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/luca/.npm/_logs/2019-07-26T07_39_12_119Z-debug.log
[ERROR] npm ERR! code ELIFECYCLE
[ERROR] npm ERR! errno 2
[ERROR] npm ERR! aaa@0.0.0 webpack:build: `npm run cleanup && npm run webpack:build:main`
[ERROR] npm ERR! Exit status 2
[ERROR] npm ERR! 
[ERROR] npm ERR! Failed at the aaa@0.0.0 webpack:build script.
[ERROR] npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[ERROR] 
[ERROR] npm ERR! A complete log of this run can be found in:
[ERROR] npm ERR!     /home/luca/.npm/_logs/2019-07-26T07_39_12_130Z-debug.log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  18.249 s
[INFO] Finished at: 2019-07-26T09:39:12+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.eirslett:frontend-maven-plugin:1.7.6:npm (webpack build dev) on project aaa: Failed to run task: 'npm run webpack:build' failed. org.apache.commons.exec.ExecuteException: Process exited with an error: 2 (Exit value: 2) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by ecostanzi** [comment]
The module has emptied the groupBy array in the
`new MergeJsonWebpackPlugin[...]` of webpack.common.js.

It should look like this (depending on the languages you have chosen):
```
         new MergeJsonWebpackPlugin({
             output: {
                 groupBy: [
                    { pattern: "./src/main/webapp/i18n/en/*.json", fileName: "./i18n/en.json" },
                    { pattern: "./src/main/webapp/i18n/it/*.json", fileName: "./i18n/it.json" }
                     // jhipster-needle-i18n-language-webpack - JHipster will add/remove languages in this array
                 ]
             }
```

**Comment by luca86r** [comment]
Restoring the missing lines fixes the problem!
